services:
  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=tradinghelper
      - POSTGRES_PASSWORD=tradinghelper
      - POSTGRES_DB=tradinghelper_dev
    #    ports:
    #    - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U tradinghelper -d tradinghelper_dev" ]
      interval: 10s
      timeout: 5s
      retries: 5

  django:
    build: ./backend
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend/:/usr/src/backend/
      - ./RiskManagement/:/usr/src/RiskManagement/
    ports:
      - 8000:8000
    env_file:
      - backend/.env.dev
    depends_on:
      db:
        condition: service_healthy

  vue:
    build: ./frontend
    volumes:
      - ./frontend/:/usr/src/frontend/
      - /usr/src/frontend/node_modules
    ports:
      - 8080:8080
    depends_on:
      - django

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile.prod
    ports:
      - "80:80"
    env_file:
      - ./nginx/.env
    depends_on:
      - django
      - db
      - vue
    volumes:
      - ./nginx/nginx-prod.conf:/etc/nginx/conf.d/default.conf.template
      - ./nginx/nginx-entrypoint.sh:/nginx-entrypoint.sh
      - ./backend/staticfiles:/home/app/backend/staticfiles
      - ./nginx/certbot/www:/var/www/certbot
      - ./nginx/certbot/conf:/etc/letsencrypt

volumes:
  postgres_data:
